### ISSUE TITLE
1.6 版本下发现有问题

### ISSUE THREAD

**Issue by wentianle** [huandu/goroutine#1]
测试所有ID 无论多少都返回 = 2 请检查一下呢，非常感谢

**Comment by wentianle** [comment]
mac os x  10.11.6 (15G31)

**Comment by wentianle** [comment]
不知道是否能支持1.6 版本的hack

**Comment by huandu** [comment]
我看看，不确定是否能支持哦。这个 hack 是针对特定版本的，如果实现变了就会发生变化。

**Comment by huandu** [comment]
看了源码，go1.6 有问题的原因是 Go 源码中 `src/runtime/runtime2.go` 的 `g` 结构发生了变化，添加了三个字段，所以读 `goid` 的偏移量出错了，读到其他字段了。这个问题不难搞定，不过我想到 go1.7 又会有类似问题，所以在做一个比较厉害的工具，彻底解决这个问题，并暴露更多能力出来。现在已经有一个 demo 做出来了，周末的时候 release 出来。

**Comment by huandu** [comment]
问题解决了，顺便支持了 1.5 ~ 1.7 所有版本。
