### ISSUE TITLE
Add risks of running this in production

### ISSUE THREAD

**Issue by Nekuromento** [huandu/goroutine#14]
Are there any risks of running this code besides locking your codebase to a particular version of runtime?
If you are aware of such risks, could you add them to repository description.
Are you aware of any companies relying on this code or similar approaches?

**Comment by huandu** [comment]
I don't recommend to use this package in any production environment unless this is the only way to solve some problems.

In most cases, it's recommended to use [context](https://golang.org/pkg/context/) to share contextual information among different functions/methods. Don't use any black magic.

If you're looking for a hack to read/write data associated with a goroutine, [gls](https://github.com/jtolds/gls) is recommended. It could be a bit less risky than this package.

Regarding to such risks, I've stated clearly in README. See the first paragraph. 😄 

> Package goroutine is merely a hack. It exports goroutine id to outside so that you can use it for whatever purpose. However, it's highly recommended to not use this package in your daily life. It may be broken at any go release as it's a hack.
