### ISSUE TITLE
重置ID号

### ISSUE THREAD

**Issue by admover** [huandu/goroutine#6]
是否可以加个重置ID号的功能，这样无限循环下去，ID号会越来越大，最好可以定期归零，比如一天归零一次？

**Comment by huandu** [comment]
这个 id 不能修改或重置，这是 Go runtime 内部维护的，需要用它来保证所有 goroutine id 的唯一性。如果觉得过大了，而且也能接受重复的 id，建议写一个自定义的 hash 函数，做一下数字转换。

例如： `f(id) = id % 10000 + 100`

这个函数就能将 id 的值限定在 [100, 10100) 范围之内了，代价是长期来看会有重复的值。

**Comment by admover** [comment]
哦，感谢，这样也行。
